services:
  appointment_business_db:
    image: postgres:17.6
    container_name: appointment_business_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appointment_business_db
      TZ: America/Hermosillo
    volumes:
      - ./server/db/files/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
